// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMWiubgGcOfFj7UxYgKTr1SspXa9olcHo',
    appId: '1:658910498061:web:b1a78883b0e46ad9faf444',
    messagingSenderId: '658910498061',
    projectId: 'biblio-share-qdbtjz',
    authDomain: 'biblio-share-qdbtjz.firebaseapp.com',
    storageBucket: 'biblio-share-qdbtjz.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2-1VclCoqT7UuExZl1NPpz9MI5GrHhHY',
    appId: '1:658910498061:android:21fe2603c3d55791faf444',
    messagingSenderId: '658910498061',
    projectId: 'biblio-share-qdbtjz',
    storageBucket: 'biblio-share-qdbtjz.appspot.com',
    androidClientId: '658910498061-t4i1iuemvmlloo2b4s0nh9lftq4i2enr.apps.googleusercontent.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAompmxAvV_SjtT6_f_R1uFkCeO8mK9PAM',
    appId: '1:658910498061:ios:7e39ae0b2c6bb2f5faf444',
    messagingSenderId: '658910498061',
    projectId: 'biblio-share-qdbtjz',
    storageBucket: 'biblio-share-qdbtjz.appspot.com',
    androidClientId: '658910498061-691r8dpki902vpr5c9fbkni3jd8j4h2a.apps.googleusercontent.com',
    iosClientId: '658910498061-der58gd1q8hnlpghoojm0n8qeberslts.apps.googleusercontent.com',
    iosBundleId: 'com.only1cent.biblioshare',
  );

}